database:
  # NAME: communication_service_db
  # USER: comms_user
  # PASS: 92aaHBwpSeODeoP
  # HOST: 10.0.1.236
  # PORT: 5432
HOST: redshift-prod.amber-data.com
PORT: 5439
USER: data_engg
PASS: Data_engg_123
NAME: amberdb

server:
  HOST: 0.0.0.0
  PORT: 5000
  DEBUG: true
